export class Family {
    constructor(famKey) {
        this._gedKey = famKey
    }
}

export class FamilyJson {
    constructor(gedrecs) {
        this._gedrecs = gedrecs
    }

    // Returns array of *content* for each matching GedcomRecord
    _all(key, context) {
        const recs = this._gedrecs.findAll(key, context)
        const contents = []
        for (let i=0; i<recs.length; i++) {
            contents.push(recs[i].content())
        }
        return contents
    }
    // Returns *content* or *missing*
    _first(key, context, missing='') {
        const rec = this._gedrecs.findFirst(key, context)
        return rec ? rec.content() : missing
    }

    // These methods return the *content* of the matched GedcomRecord or records
    xKey(famKey) { return this._first(famKey, ['FAM', 'WIFE']) }
    yKey(famKey) { return this._first(famKey, ['FAM', 'HUSB']) }
    childKeys(famKey) { return this._all(famKey, ['FAM', 'CHIL'])}
    divDate(famKey) { return this._first(famKey, ['FAM', 'DIV', 'DATE']) }
    divNote(famKey) { return this._first(famKey, ['FAM', 'DIV', 'NOTE']) }
    divPlace(famKey) { return this._first(famKey, ['FAM', 'DIV', 'PLAC']) }
    divSources(famKey) { return this._all(famKey, ['FAM', 'DIV', 'SOUR']) }
    marrDate(famKey) { return this._first(famKey, ['FAM', 'MARR', 'DATE']) }
    marrNote(famKey) { return this._first(famKey, ['FAM', 'MARR', 'NOTE']) }
    marrPlace(famKey) { return this._first(famKey, ['FAM', 'MARR', 'PLAC']) }
    marrSources(famKey) { return this._all(famKey, ['FAM', 'MARR', 'SOUR']) }

    // Hydrates a family object into a Family instance by hydrating all keys into references
    hydrate(family) {

    }

    // Returns a JSON object containing all the FAM data for a famKey '@Fn@' that can be stringified
    toJson(famKey) {
        const family = {
            xKey: this.xKey(famKey),
            yKey: this.yKey(famKey),
            childKeys: this.childKeys(famKey),
            union: {
                date: this.marrDate(famKey),
                note: this.marrNote(famKey),
                place: this.marrPlace(famKey),
                sources: this.marrSources(famKey)
            },
            split: {
                date: this.divDate(famKey),
                note: this.divNote(famKey),
                place: this.divPlace(famKey),
                sources: this.divSources(famKey)
            }
        }
        return family
    }

    // Returns an array of all the FAM record objects, which may be stringified as its not hydrated.
    toJsonArray() {
        const families = []
        const famMap = this._gedrecs.topLevelRecordsFor('FAM')
        for(const famKey of famMap.keys()) families.push(this.toJson(famKey))
        return families
    }

    // Returns a stringified plain old JSON object embedded inside a Javascript declaration
    toJsonFile(indent=0, varName='gedJson') {
        const famArr = this.toJsonArray()
        let text = `// auto-generated by FamilyJson.toJsonFile() on ${new Date().toLocaleString()}\n`
        text += `export const ${varName} = {\n`
        text += `family: ${JSON.stringify(famArr, null, indent)},\n`
        text += '}'
        return text
    }

    // Returns a Map object whith FAM '@F123@' keys and hydrated family records
    toMap() {
        const map = new Map()
        const famMap = this._gedrecs.topLevelRecordsFor('FAM')
        for(const famKey of famMap.keys()) map.set(famKey, this.toJson(famKey))
        return map
    }
}